In [32]:
import numpy as np 
import pandas as pd
import matplotlib.pyplot as plt
%matplotlib qt

In [4]:
 ar= np.arange(1,20,2)

IndentationError: unexpected indent (<ipython-input-4-4e8ba85f3447>, line 2)

In [5]:
ar

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19])

In [6]:
ar.reshape(5,2)

array([[ 1,  3],
       [ 5,  7],
       [ 9, 11],
       [13, 15],
       [17, 19]])

In [10]:
a= np.arange(0,60,10).reshape(-1,1) + np.arange(0,6)

In [11]:
a


array([[ 0,  1,  2,  3,  4,  5],
       [10, 11, 12, 13, 14, 15],
       [20, 21, 22, 23, 24, 25],
       [30, 31, 32, 33, 34, 35],
       [40, 41, 42, 43, 44, 45],
       [50, 51, 52, 53, 54, 55]])

IndexError: index 6 is out of bounds for axis 1 with size 6

In [16]:
na=np.array(['A','B','C','D','E','F','C'])
na=='C'

array([False, False,  True, False, False, False,  True], dtype=bool)

In [17]:
a.T

array([[ 0, 10, 20, 30, 40, 50],
       [ 1, 11, 21, 31, 41, 51],
       [ 2, 12, 22, 32, 42, 52],
       [ 3, 13, 23, 33, 43, 53],
       [ 4, 14, 24, 34, 44, 54],
       [ 5, 15, 25, 35, 45, 55]])

In [10]:
p=np.arange(-5,5,0.01)
x,y=np.meshgrid(p,p)
z=np.sqrt(x**2+y**2)
plt.imshow(z,cmap=plt.cm.gray);plt.colorbar()
plt.title("image plot of $\sqrt{x^2+y^2}$ for a grid of values")

In [16]:
xw=np.arange(-5,-20,-5)
yw=np.arange(5,20,5)
cond=np.array([True,True,False])
np.where(cond,yw,xw)


array([  5,  10, -15])

In [25]:
from numpy.linalg import eig,inv,qr,det
w=np.array([[1,2,2],[2,3,4],[3,4,5]])
eig(w)

(array([ 9.33292329+0.j        , -0.16646165+0.28184763j,
        -0.16646165-0.28184763j]),
 array([[-0.31890305+0.j        ,  0.69283737+0.j        ,  0.69283737-0.j        ],
        [-0.57608048+0.j        , -0.10615790+0.50443928j,
         -0.10615790-0.50443928j],
        [-0.75261685+0.j        , -0.29792621-0.406802j  ,
         -0.29792621+0.406802j  ]]))

In [28]:
w

array([[1, 2, 2],
       [2, 3, 4],
       [3, 4, 5]])

In [37]:
inv(w).dtype(int8)

NameError: name 'int8' is not defined

In [35]:
from pandas import Series,DataFrame
obj=Series([1,2,3,4])


In [36]:
obj

0    1
1    2
2    3
3    4
dtype: int64